version: '3.9'

services:
  db:
    extends:
      file: docker-common.yml
      service: db
    volumes:
      - kingsystem_db:/var/lib/postgresql/data
  nest:
    extends:
      file: docker-common.yml
      service: nest

volumes:
  kingsystem_db: