version: '3.9'

services:
  db:
    extends:
      file: docker-common.yml
      service: db
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - kingsystem_db_test:/var/lib/postgresql/data
  nest:
    extends:
      file: docker-common.yml
      service: nest
    build:
      context: .
      target: development
    restart: no
    working_dir: /app
    command: sh -c "npm run prisma:reset && npm run test:e2e"
    volumes:
      - ./test:/app/test

volumes:
  kingsystem_db_test: