version: '3.9'

services:
  db:
    extends:
      file: docker-common.yml
      service: db
    volumes:
      - kingsystem_db_dev:/var/lib/postgresql/data
  nest:
    extends:
      file: docker-common.yml
      service: nest
    build:
      context: .
      target: development
    working_dir: /app
    command: sh -c "npm run prisma:migrate && npm run start:dev"
    volumes:
      - .:/app

volumes:
  kingsystem_db_dev: