services:
  db:
    image: postgres:14-alpine
    container_name: kingsystem_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  nest:
    build: .
    image: devsbaraus/kingsystem_nest
    container_name: kingsystem_nest
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_HOST=db
    depends_on:
      db:
        condition: service_healthy