version: '3.9'

services:
  db:
    extends:
      file: docker-common.yml
      service: db
    volumes:
      - kingsystem_db:/var/lib/postgresql/data
  nest:
    extends:
      file: docker-common.yml
      service: nest
    working_dir: /app
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  kingsystem_db:
    external: true