name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: "kingsystem"
      DATABASE_PASS: "kingsystem"
      DATABASE_USER: "kingsystem"
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      DATABASE_URL: "postgresql://kingsystem:kingsystem@db:5432/kingsystem?schema=public"
      JWT_SECRET: "secret"
      JWT_EXPIRES_IN: "1d"
      APP_PORT: 3000
      APP_PAGE_SIZE: 10
      COMPOSE_FILE: docker-compose.test.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DATABASE_NAME=${DATABASE_NAME}" >> .env \
          echo "DATABASE_PASS=${DATABASE_PASS}" >> .env \
          echo "DATABASE_USER=${DATABASE_USER}" >> .env \
          echo "DATABASE_PORT=${DATABASE_PORT}" >> .env \
          echo "DATABASE_HOST=${DATABASE_HOST}" >> .env \
          echo "DATABASE_URL=${DATABASE_URL}" >> .env \
          echo "JWT_SECRET=${JWT_SECRET}" >> .env \
          echo "JWT_EXPIRES_IN=${JWT_EXPIRES_IN}" >> .env \
          echo "APP_PORT=${APP_PORT}" >> .env \
          echo "APP_PAGE_SIZE=${APP_PAGE_SIZE}" >> .env

      - name: Cat .env file
        run: cat .env

      - name: Build docker images
        run: docker compose build

      - name: Run tests
        run: docker compose run nest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}